local LSM = LibStub('LibSharedMedia-3.0')

LSM:Register('statusbar', 'Asphyxia', [[Interface\AddOns\DSM\Media\StatusBars\Asphyxia]])
LSM:Register('statusbar', 'Bezo', [[Interface\AddOns\DSM\Media\StatusBars\Bezo]])
LSM:Register('statusbar', 'Dajova', [[Interface\AddOns\DSM\Media\StatusBars\Dajova]])
LSM:Register('statusbar', 'Duffed', [[Interface\AddOns\DSM\Media\StatusBars\Duffed]])
LSM:Register('statusbar', 'Flatt', [[Interface\AddOns\DSM\Media\StatusBars\Flatt]])
LSM:Register('statusbar', 'Sinaris', [[Interface\AddOns\DSM\Media\StatusBars\Sinaris]])
LSM:Register('statusbar', 'Slate', [[Interface\AddOns\DSM\Media\StatusBars\Slate]])
LSM:Register('statusbar', 'Smooth', [[Interface\AddOns\DSM\Media\StatusBars\Smooth]])
LSM:Register('statusbar', 'Tukui', [[Interface\AddOns\DSM\Media\StatusBars\Tukui]])

LSM:Register('statusbar', 'Aluminium Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Aluminium]])
LSM:Register('statusbar', 'Asphyxia Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Asphyxia]])
LSM:Register('statusbar', 'BantoBar Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\BantoBar]])
LSM:Register('statusbar', 'Button Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Button]])
LSM:Register('statusbar', 'Cloud Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Cloud]])
LSM:Register('statusbar', 'Comet Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Comet]])
LSM:Register('statusbar', 'Dabs Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Dabs]])
LSM:Register('statusbar', 'ElvUI Gloss Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\ElvUI]])
LSM:Register('statusbar', 'Falumn Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Falumn]])
LSM:Register('statusbar', 'Flat Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Flat]])
LSM:Register('statusbar', 'Frost Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Frost]])
LSM:Register('statusbar', 'Glamour Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour]])
LSM:Register('statusbar', 'Glamour2 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour2]])
LSM:Register('statusbar', 'Glamour3 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour3]])
LSM:Register('statusbar', 'Glamour4 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour4]])
LSM:Register('statusbar', 'Glamour5 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour5]])
LSM:Register('statusbar', 'Glamour6 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour6]])
LSM:Register('statusbar', 'Glamour7 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glamour7]])
LSM:Register('statusbar', 'Glaze Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glaze]])
LSM:Register('statusbar', 'Glaze2 Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Glaze2]])
LSM:Register('statusbar', 'Gloss Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Gloss]])
LSM:Register('statusbar', 'Healbot Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Healbot]])
LSM:Register('statusbar', 'LiteStep Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\LiteStep]])
LSM:Register('statusbar', 'Lyfe Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Lyfe]])
LSM:Register('statusbar', 'Minimalist Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Minimalist]])
LSM:Register('statusbar', 'Otravi Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Otravi]])
LSM:Register('statusbar', 'Outline Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Outline]])
LSM:Register('statusbar', 'Perl Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Perl]])
LSM:Register('statusbar', 'Rocks Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Rocks]])
LSM:Register('statusbar', 'Round Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Round]])
LSM:Register('statusbar', 'Ruben Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Ruben]])
LSM:Register('statusbar', 'Runes Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Runes]])
LSM:Register('statusbar', 'Sinaris Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Sinaris]])
LSM:Register('statusbar', 'Slate Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Slate]])
LSM:Register('statusbar', 'Smooth Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Smooth]])
LSM:Register('statusbar', 'Tukui Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Tukui]])
LSM:Register('statusbar', 'Water Vertical', [[Interface\AddOns\DSM\Media\StatusBars\Vertical\Water]])

LSM:Register('font', 'Big Noodle Titling', [[Interface\AddOns\DSM\Media\Fonts\BigNoodleTitling.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Dajova', [[Interface\AddOns\DSM\Media\Fonts\Dajova.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Oswald Bold', [[Interface\AddOns\DSM\Media\Fonts\Oswald-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Oswald Light', [[Interface\AddOns\DSM\Media\Fonts\Oswald-Light.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Oswald Regular', [[Interface\AddOns\DSM\Media\Fonts\Oswald-Regular.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Saarland', [[Interface\AddOns\DSM\Media\Fonts\Saarland.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Samson', [[Interface\AddOns\DSM\Media\Fonts\Samson.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Sony Sketch', [[Interface\AddOns\DSM\Media\Fonts\SonySketch.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'PT Sans Narrow Bold', [[Interface\AddOns\DSM\Media\Fonts\PTSansNarrow-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Diediedie', [[Interface\AddOns\DSM\Media\Fonts\Diediedie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Visitor TT2 BRK', [[Interface\AddOns\DSM\Media\Fonts\Visitor.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Homespun TT BRK', [[Interface\AddOns\DSM\Media\Fonts\Homespun.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Action Man', [[Interface\AddOns\DSM\Media\Fonts\ActionMan.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Continuum Medium', [[Interface\AddOns\DSM\Media\Fonts\ContinuumMedium.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Arial', [[Interface\AddOns\DSM\Media\Fonts\Arial.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'KGSmallTownSouthernGirl', [[Interface\AddOns\DSM\Media\Fonts\KGSmallTownSouthernGirl.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Youthanasia Texture', [[Interface\AddOns\DSM\Media\Fonts\YOUTHAN.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Youthanasia Texture Regular', [[Interface\AddOns\DSM\Media\Fonts\YOUTTX.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Good Time', [[Interface\AddOns\DSM\Media\Fonts\GOODTIME.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Reprise Title', [[Interface\AddOns\DSM\Media\Fonts\Reprise Title.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Futurapress', [[Interface\AddOns\DSM\Media\Fonts\Futurapress.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Event Horizon', [[Interface\AddOns\DSM\Media\Fonts\Event Horizon.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'H.H. Samuel', [[Interface\AddOns\DSM\Media\Fonts\H.H. Samuel.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Jacinto Sans', [[Interface\AddOns\DSM\Media\Fonts\Jacinto Sans.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'JUSTICE LEAGUE', [[Interface\AddOns\DSM\Media\Fonts\JUSTICE LEAGUE.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'SF Laundromatic Condensed', [[Interface\AddOns\DSM\Media\Fonts\SF Laundromatic Condensed.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Skipper Stencil', [[Interface\AddOns\DSM\Media\Fonts\skipper_stencil.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Ardnas', [[Interface\AddOns\DSM\Media\Fonts\Ardnas.otf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Impacted', [[Interface\AddOns\DSM\Media\Fonts\Impacted.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Lemondrop', [[Interface\AddOns\DSM\Media\Fonts\Lemondrop.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Mobile Sans', [[Interface\AddOns\DSM\Media\Fonts\Mobile Sans.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Quimbie', [[Interface\AddOns\DSM\Media\Fonts\Quimbie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Monserga Regular', [[Interface\AddOns\DSM\Media\Fonts\Monserga-regular-FFP.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Indulta SemiSerif', [[Interface\AddOns\DSM\Media\Fonts\Indulta-SemiSerif-boldFFP.otf]])
LSM:Register('font', 'CLUB', [[Interface\AddOns\DSM\Media\Fonts\CLUB____.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Adigiana Ultra', [[Interface\AddOns\DSM\Media\Fonts\Adigiana Ultra.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Tabarra Shadow', [[Interface\AddOns\DSM\Media\Fonts\Tabarra-Shadow-FFP.otf]])
LSM:Register('font', 'Sturkopf', [[Interface\AddOns\DSM\Media\Fonts\Sturkopf.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Ordinatum Bold', [[Interface\AddOns\DSM\Media\Fonts\Ordinatum_Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Ordinatum Light', [[Interface\AddOns\DSM\Media\Fonts\Ordinatum_Light.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Ordinatum Medium', [[Interface\AddOns\DSM\Media\Fonts\Ordinatum_Medium.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Zektonbo', [[Interface\AddOns\DSM\Media\Fonts\zektonbo.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Aron Grotesque Bold', [[Interface\AddOns\DSM\Media\Fonts\aron_grotesque_bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'AIdealist Sans', [[Interface\AddOns\DSM\Media\Fonts\Idealist Sans.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Sarpanch SemiBold', [[Interface\AddOns\DSM\Media\Fonts\Sarpanch-SemiBold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Semi Casual', [[Interface\AddOns\DSM\Media\Fonts\Semi-Casual.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'futurademic', [[Interface\CustomFonts\Semi-Casual.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-Bold', [[Interface\CustomFonts\OpenSans-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-BoldItalic', [[Interface\CustomFonts\OpenSans-BoldItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-ExtraBold', [[Interface\CustomFonts\OpenSans-ExtraBold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-ExtraBoldItalic', [[Interface\CustomFonts\OpenSans-ExtraBoldItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-Italic', [[Interface\CustomFonts\OpenSans-Italic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-Light', [[Interface\CustomFonts\OpenSans-Light.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-LightItalic', [[Interface\CustomFonts\OpenSans-LightItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-Regular', [[Interface\CustomFonts\OpenSans-Regular.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-Semibold', [[Interface\CustomFonts\OpenSans-Semibold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'OpenSans-SemiboldItalic', [[Interface\CustomFonts\OpenSans-SemiboldItalic.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Supermolot', [[Interface\AddOns\DSM\Media\Fonts\Supermolot.otf]])

LSM:Register('sound', 'Warning', [[Interface\AddOns\DSM\Media\Sounds\Warning.mp3]])
LSM:Register('sound', 'Тройная дизмораль', [[Interface\AddOns\DSM\Media\Sounds\Voodoshtripple.mp3]])
LSM:Register('sound', 'Миша ну БАБЛ', [[Interface\AddOns\DSM\Media\Sounds\mishababl.mp3]])
LSM:Register('sound', 'Ааааа Вопль', [[Interface\AddOns\DSM\Media\Meme\AAAA_lew.ogg]])
LSM:Register('sound', 'Ааааа Гачи', [[Interface\AddOns\DSM\Media\Meme\AAAAA.ogg]])
LSM:Register('sound', 'Ты Арестован Парень', [[Interface\AddOns\DSM\Media\Meme\arestovan.ogg]])
LSM:Register('sound', 'Ты Баклажан', [[Interface\AddOns\DSM\Media\Meme\baklazhan.ogg]])
LSM:Register('sound', 'Бляяяять', [[Interface\AddOns\DSM\Media\Meme\bearform.ogg]])
LSM:Register('sound', 'Блейдшторм', [[Interface\AddOns\DSM\Media\Meme\bladestorm.ogg]])
LSM:Register('sound', 'Бочок Потик', [[Interface\AddOns\DSM\Media\Meme\bochok.ogg]])
LSM:Register('sound', 'Бомба Раздефужена', [[Interface\AddOns\DSM\Media\Meme\bomb_d.ogg]])
LSM:Register('sound', 'Бомба Установлена', [[Interface\AddOns\DSM\Media\Meme\bomb_p.ogg]])
LSM:Register('sound', 'Чики Брики', [[Interface\AddOns\DSM\Media\Meme\cheeki-breeki.ogg]])
LSM:Register('sound', 'Чего Блять', [[Interface\AddOns\DSM\Media\Meme\chegob.ogg]])
LSM:Register('sound', 'Циган Айдидидай', [[Interface\AddOns\DSM\Media\Meme\cigan.ogg]])
LSM:Register('sound', 'Убирай Дрочило', [[Interface\AddOns\DSM\Media\Meme\disarm.ogg]])
LSM:Register('sound', 'Снимай штаны и доставай', [[Interface\AddOns\DSM\Media\Meme\disarm_2.ogg]])
LSM:Register('sound', 'Диджей Ебан', [[Interface\AddOns\DSM\Media\Meme\djeban.ogg]])
LSM:Register('sound', 'У меня Джип', [[Interface\AddOns\DSM\Media\Meme\djeep.ogg]])
LSM:Register('sound', 'Lot of Damage', [[Interface\AddOns\DSM\Media\Meme\dmg.ogg]])
LSM:Register('sound', 'Dps slowly', [[Interface\AddOns\DSM\Media\Meme\dpsslowly.ogg]])
LSM:Register('sound', 'Dramartic', [[Interface\AddOns\DSM\Media\Meme\dramartic.ogg]])
LSM:Register('sound', 'Нахуя Дудосить', [[Interface\AddOns\DSM\Media\Meme\dudos.ogg]])
LSM:Register('sound', 'Йобаный рот', [[Interface\AddOns\DSM\Media\Meme\ebany_rot.ogg]])
LSM:Register('sound', 'Enemy spoted', [[Interface\AddOns\DSM\Media\Meme\enemy_spot.ogg]])
LSM:Register('sound', 'Ержан вставай', [[Interface\AddOns\DSM\Media\Meme\erjan.ogg]])
LSM:Register('sound', 'FBI опен ап', [[Interface\AddOns\DSM\Media\Meme\FBI.ogg]])
LSM:Register('sound', 'Беги сука беги', [[Interface\AddOns\DSM\Media\Meme\fear2.ogg]])
LSM:Register('sound', 'Это фиаско братан', [[Interface\AddOns\DSM\Media\Meme\fiasco.ogg]])
LSM:Register('sound', 'Граната из КС', [[Interface\AddOns\DSM\Media\Meme\fireinthe.ogg]])
LSM:Register('sound', 'Прекрати разврат', [[Interface\AddOns\DSM\Media\Meme\greshnik.ogg]])
LSM:Register('sound', 'Хардбас', [[Interface\AddOns\DSM\Media\Meme\hardbass.ogg]])
LSM:Register('sound', 'Попробуй меня трахнуть', [[Interface\AddOns\DSM\Media\Meme\idisuda.ogg]])
LSM:Register('sound', 'Имолейт Импрувед', [[Interface\AddOns\DSM\Media\Meme\impruved.ogg]])
LSM:Register('sound', 'Джон Сина', [[Interface\AddOns\DSM\Media\Meme\jhoncena.ogg]])
LSM:Register('sound', 'Ты внатуре кабан', [[Interface\AddOns\DSM\Media\Meme\kaban.ogg]])
LSM:Register('sound', 'Давай прыгай', [[Interface\AddOns\DSM\Media\Meme\kakashka.ogg]])
LSM:Register('sound', 'Да каке ебнуть', [[Interface\AddOns\DSM\Media\Meme\kakebnut.ogg]])
LSM:Register('sound', 'Как так то а', [[Interface\AddOns\DSM\Media\Meme\kaktak.ogg]])
LSM:Register('sound', 'Ебаный рот казино', [[Interface\AddOns\DSM\Media\Meme\kazino_1.ogg]])
LSM:Register('sound', 'Ебаный твой рот', [[Interface\AddOns\DSM\Media\Meme\kazino_2.ogg]])
LSM:Register('sound', 'Kill Them', [[Interface\AddOns\DSM\Media\Meme\killthem.ogg]])
LSM:Register('sound', 'Пошел ты козел', [[Interface\AddOns\DSM\Media\Meme\kozel.ogg]])
LSM:Register('sound', 'Левиосаааа', [[Interface\AddOns\DSM\Media\Meme\leviosa.ogg]])
LSM:Register('sound', 'Ватафакмазафак', [[Interface\AddOns\DSM\Media\Meme\mazafak.ogg]])
LSM:Register('sound', 'По новой Миша', [[Interface\AddOns\DSM\Media\Meme\misha.ogg]])
LSM:Register('sound', 'Мор Дотс', [[Interface\AddOns\DSM\Media\Meme\moredots.ogg]])
LSM:Register('sound', 'Муда муда муда', [[Interface\AddOns\DSM\Media\Meme\muda.ogg]])
LSM:Register('sound', 'Ну Нахер', [[Interface\AddOns\DSM\Media\Meme\naher.ogg]])
LSM:Register('sound', 'Нормально', [[Interface\AddOns\DSM\Media\Meme\namalno.ogg]])
LSM:Register('sound', 'нет Мозга', [[Interface\AddOns\DSM\Media\Meme\netmozga.ogg]])
LSM:Register('sound', 'Невыдерживаю', [[Interface\AddOns\DSM\Media\Meme\neviderj.ogg]])
LSM:Register('sound', 'Нойс', [[Interface\AddOns\DSM\Media\Meme\noice.ogg]])
LSM:Register('sound', 'Майнкрафт урон', [[Interface\AddOns\DSM\Media\Meme\oh.ogg]])
LSM:Register('sound', 'Айм Сори', [[Interface\AddOns\DSM\Media\Meme\ohshit.ogg]])
LSM:Register('sound', 'Омаоа шиндеау', [[Interface\AddOns\DSM\Media\Meme\omaeva.ogg]])
LSM:Register('sound', 'Отходите пожалуйста', [[Interface\AddOns\DSM\Media\Meme\othodi.ogg]])
LSM:Register('sound', 'Палку давай', [[Interface\AddOns\DSM\Media\Meme\palku.ogg]])
LSM:Register('sound', 'Пизда Рулю', [[Interface\AddOns\DSM\Media\Meme\pizdaruly.ogg]])
LSM:Register('sound', 'Отходите подальше', [[Interface\AddOns\DSM\Media\Meme\podalshe.ogg]])
LSM:Register('sound', 'Покайся Грешник', [[Interface\AddOns\DSM\Media\Meme\pokaysya.ogg]])
LSM:Register('sound', 'Погнали нахуй', [[Interface\AddOns\DSM\Media\Meme\pull.ogg]])
LSM:Register('sound', 'Мужицкий дождь', [[Interface\AddOns\DSM\Media\Meme\rain.ogg]])
LSM:Register('sound', 'Крайне мала', [[Interface\AddOns\DSM\Media\Meme\resist.ogg]])
LSM:Register('sound', 'Ран', [[Interface\AddOns\DSM\Media\Meme\run.ogg]])
LSM:Register('sound', 'Че серьезно', [[Interface\AddOns\DSM\Media\Meme\serezno.ogg]])
LSM:Register('sound', 'Шааааааа', [[Interface\AddOns\DSM\Media\Meme\sha.ogg]])
LSM:Register('sound', 'Снуп Дог', [[Interface\AddOns\DSM\Media\Meme\snoopdog.ogg]])
LSM:Register('sound', 'Стартуем', [[Interface\AddOns\DSM\Media\Meme\startyem.ogg]])
LSM:Register('sound', 'Время стопать', [[Interface\AddOns\DSM\Media\Meme\stop.ogg]])
LSM:Register('sound', 'ШАФЕР БИТЧ', [[Interface\AddOns\DSM\Media\Meme\suffer_bitch.ogg]])
LSM:Register('sound', 'Сурпрайз Мазафака', [[Interface\AddOns\DSM\Media\Meme\surprise.ogg]])
LSM:Register('sound', 'Тааааааа', [[Interface\AddOns\DSM\Media\Meme\taa.ogg]])
LSM:Register('sound', 'Ю тач май тралала', [[Interface\AddOns\DSM\Media\Meme\talala.ogg]])
LSM:Register('sound', 'Продолжение следует', [[Interface\AddOns\DSM\Media\Meme\tobecon.ogg]])
LSM:Register('sound', 'Толик Еболик', [[Interface\AddOns\DSM\Media\Meme\tolik.ogg]])
LSM:Register('sound', 'Ама вирджин', [[Interface\AddOns\DSM\Media\Meme\virgin.ogg]])
LSM:Register('sound', 'Больно в ноге', [[Interface\AddOns\DSM\Media\Meme\vnoge.ogg]])
LSM:Register('sound', 'Велком ту зе клаб', [[Interface\AddOns\DSM\Media\Meme\welcome.ogg]])
LSM:Register('sound', 'Вау', [[Interface\AddOns\DSM\Media\Meme\wow.ogg]])
LSM:Register('sound', 'Я вас не звал', [[Interface\AddOns\DSM\Media\Meme\ya_vas_ne_zval.ogg]])
LSM:Register('sound', 'Яйцами пезднулся', [[Interface\AddOns\DSM\Media\Meme\yaytsami.ogg]])

LSM:Register('font', 'Tukui Pixel', [[Interface\AddOns\DSM\Media\Fonts\Visitor.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Tukui Combat', [[Interface\AddOns\DSM\Media\Fonts\Diediedie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font', 'Tukui UnitFrame', [[Interface\AddOns\DSM\Media\Fonts\BigNoodleTitling.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)

if not select(4, GetAddOnInfo('ElvUI')) then
	LSM:Register('font', 'ElvUI Alt-Combat', [[Interface\AddOns\DSM\Media\Fonts\Diediedie.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register('font', 'ElvUI Alt-Font', [[Interface\AddOns\DSM\Media\Fonts\ContinuumMedium.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register('font', 'ElvUI Combat', [[Interface\AddOns\DSM\Media\Fonts\ActionMan.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register('font', 'ElvUI Font', [[Interface\AddOns\DSM\Media\Fonts\PTSansNarrow-Bold.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register('font', 'ElvUI Pixel', [[Interface\AddOns\DSM\Media\Fonts\Homespun.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
	LSM:Register('statusbar', 'ElvUI Gloss', [[Interface\AddOns\DSM\Media\StatusBars\ElvUI]])
end